---

- include: repo.yaml

- name: Create mcrouter configuration
  template:
      src: templates/mcrouter.conf.j2
      dest: /etc/mcrouter.conf
      owner: root
      group: root
      mode: 0644

- name: Install mcrouter
  apt:
      name: "mcrouter={{ mcrouter_version }}"
      state: present

- name: Create systemd unit configuration
  template:
      src: templates/mcrouter.service.j2
      dest: etc/systemd/system/mcrouter.service
      owner: root
      group: root
      mode: 0644

- name: systemd daemon reload and start service
  systemd:
      name: mcrouter
      state: restarted
      enabled: yes
      daemon_reload: yes