---
# vars file for Memcached
memcache_pool_str: '{% for item in range(size|int) %}"{{ meta.name }}-memcached-{{ item }}.{{ meta.name }}-memcached.{{ meta.namespace }}.svc.cluster.local:11211"{% if not loop.last%},{% endif %}{% endfor %}'
