apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mcrouters.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: Mcrouter
    listKind: McrouterList
    plural: mcrouters
    singular: mcrouter
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
