apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mcrouters.mcrouter.example.com
spec:
  group: mcrouter.example.com
  names:
    kind: Mcrouter
    listKind: McrouterList
    plural: mcrouters
    singular: mcrouter
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
