---
# tasks file for Mcrouter
- name: start memcached
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: cache
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: memcached
        template:
          metadata:
            labels:
              app: memcached
          spec:
            containers:
            - name: memcached
              command:
              - memcached
              - -m=64
              - -o
              - modern
              - -v
              image: "memcached:1.4.36-alpine"
              ports:
                - containerPort: 11211

- name: start cache service
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: cache
        namespace: '{{ meta.namespace }}'
      spec:
        ports:
        - port: 11211
          protocol: TCP
        selector:
          matchLabels:
          app: memcached
