---
# tasks file for Mcrouter
- name: start mcrouter
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-mcrouter'
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: mcrouter
        template:
          metadata:
            labels:
              app: mcrouter
          spec:
            containers:
            - name: mcrouter
              command:
              - mcrouter
              - --config-str={"pools":{"A":{"servers":["cache:11211"]}},"route":"PoolRoute|A"}
              - -p
              - "5000"
              image: "devan2502/mcrouter:latest"
              ports:
                - containerPort: 5000
